# Generated by Django 4.2.9 on 2024-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_redesign', '0002_productimage_image_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='app_redesign/static/product_images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
